# Generated by Django 5.2.16 on 2026-08-01 09:48

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = []

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("done", models.BooleanField(default=False)),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Low"), (2, "Medium"), (3, "High")],
                        null=True,
                    ),
                ),
            ],
        ),
    ]
